name: 13-caching
on: 
    workflow_dispatch:
        inputs:
            use-cache:
                type: boolean
                description: Whether to execute cache step
                default: true
            node-version:
                type: choice
                options:
                    - 18.x
                    - 20.x
                    - 21.x
jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: 13-caching/react-app
        steps:
            - name: checkout code
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                node-version: ${{inputs.node-version}}
            
            - name: Downloaded Cached Dependencies
              uses: actions/cache@v3
              if: ${{inputs.use-cache}}
              id: cache
              with:
                path : 13-caching/react-app/node_modules
                key: deps-node-modules-${{hashfiles('13-caching/react-app/package-lock.json')}}

            - name: Install dependencies
              if: steps.cache.outputs.cache-hit!= 'true'
              run: |
               npm ci
               echo "install dependencies" 
            - name: Testing
              run: npm run test
            - name: Building
              run: npm run build
            - name: Deploy to non prod
              run: |
               echo "Deploying to Non Prod"



