name: 16 - Working with Environments
run-name: 16 - Wking with Env | env - ${{inputs.target-env}}
on:
    workflow_dispatch:
        inputs:
            target-env:
                type: environment
                default: staging
jobs:
    echo:
        runs-on: ubuntu-latest
        environment: ${{inputs.target-env}}
        env:
            my-env-variable: ${{ vars.MY_ENV_VALUE || 'default value' }} 
        steps:
            - name: Echo vars
              run: |
               echo "Environment Variable : ${{env.my-env-variable}}"


